pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()

        maven {
            url = "https://maven.pkg.github.com/surepassio/digiboost-sample-app"
            credentials {
                username = "YOUR USERNAME"
                password = "YOUR PAT TOKEN"
            }
        }
    }
}
rootProject.name = "Digilocker Sample App"
include ':app'
